<?php

namespace Metrial\RBAC\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

class IdeHelperCommand extends Command
{
    protected $signature = 'rbac:ide-helper';

    protected $description = 'Generate IDE helper file for HasRoles trait and Facade autocompletion';

    public function handle(Filesystem $files): int
    {
        $content = <<<'PHP'
<?php

// This file is auto-generated by `php artisan rbac:ide-helper`.
// Do not edit manually. It will be overwritten.

namespace Illuminate\Database\Eloquent {
    /**
     * @method \Metrial\RBAC\Models\Role|\Illuminate\Support\Collection assignRole(string|\Metrial\RBAC\Models\Role $role, ?\Metrial\RBAC\Models\Team $team = null, ?string $guard = null, ?\DateTimeInterface $startsAt = null, ?\DateTimeInterface $expiresAt = null)
     * @method void removeRole(string|\Metrial\RBAC\Models\Role $role, ?\Metrial\RBAC\Models\Team $team = null)
     * @method void syncRoles(array $roles, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasRole(string|\Metrial\RBAC\Models\Role|array $roles, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasAllRoles(array $roles, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasAnyRole(array $roles, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasPermissionTo(string|\Metrial\RBAC\Models\Permission $permission, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasAnyPermission(array $permissions, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasDirectPermission(string|\Metrial\RBAC\Models\Permission $permission, ?\Metrial\RBAC\Models\Team $team = null)
     * @method bool hasWildcardPermission(string $permissionName, ?\Metrial\RBAC\Models\Team $team = null)
     * @method void givePermissionTo(string|\Metrial\RBAC\Models\Permission $permission, ?\Metrial\RBAC\Models\Team $team = null, ?string $guard = null, ?\DateTimeInterface $startsAt = null, ?\DateTimeInterface $expiresAt = null)
     * @method void revokePermissionTo(string|\Metrial\RBAC\Models\Permission $permission, ?\Metrial\RBAC\Models\Team $team = null)
     * @method void syncPermissions(array $permissions, ?\Metrial\RBAC\Models\Team $team = null)
     * @method void addToTeam(\Metrial\RBAC\Models\Team $team, bool $asOwner = false)
     * @method void removeFromTeam(\Metrial\RBAC\Models\Team $team)
     * @method bool isMemberOf(\Metrial\RBAC\Models\Team $team)
     * @method bool isOwnerOf(\Metrial\RBAC\Models\Team $team)
     * @method $this switchTeam(?\Metrial\RBAC\Models\Team $team)
     * @method string|null getActiveTeamId()
     * @method \Illuminate\Support\Collection getPermissions(?\Metrial\RBAC\Models\Team $team = null)
     * @method \Illuminate\Support\Collection getRoles(?\Metrial\RBAC\Models\Team $team = null)
     * @method \Illuminate\Database\Eloquent\Relations\MorphToMany roles()
     * @method \Illuminate\Database\Eloquent\Relations\MorphToMany teams()
     * @method \Illuminate\Database\Eloquent\Relations\MorphToMany teamMemberships()
     * @method \Illuminate\Database\Eloquent\Relations\MorphToMany permissions()
     */
    trait HasTeams {}
}

namespace {
    /**
     * @method static \Metrial\RBAC\Services\RoleService role()
     * @method static \Metrial\RBAC\Services\PermissionService permission()
     * @method static \Metrial\RBAC\Services\AssignmentService assignment()
     * @method static \Metrial\RBAC\Services\TeamService team()
     * @method static \Metrial\RBAC\Services\AuditService audit()
     */
    class Rbac extends \Metrial\RBAC\Facades\Rbac {}
}
PHP;

        $path = base_path('_ide_helper_rbac.php');
        $files->put($path, $content);

        $this->info("IDE helper file generated at: {$path}");
        $this->line('Add "_ide_helper_rbac.php" to your .gitignore.');

        return self::SUCCESS;
    }
}
